### PR TITLE
chome for android notification

### PR DESCRIPTION
**Pull request by xxyzz**
screenshot_20171212-134525

### CODE REVIEW

**Comment by jacksonhvisuals** [comment]
Planning to add a toggle?

**Comment by xxyzz** [comment]
A toggle? Do you mean that it should have a button to enable or disable the notification?

**Comment by jacksonhvisuals** [comment]
Yep. (That is what Jeff was referring to)

**Comment by jacksonhvisuals** [comment]
Since there's a bit of UI & settings work that is a bit in-depth and hard to explain, I decided to implement a variation of your work myself.

**Pull request closed without merging**
